### PR TITLE
Issue 140.dockter.1

### PR DESCRIPTION
**Pull request by docktermj**
# Pull request questions

## Which issue does this address

Issue number: #140

### CODE REVIEW

**Review by roncewind — CHANGES_REQUESTED** [review]
did you intend to check in an empty notes.txt file?

**Review by roncewind — COMMENTED** [review]
also:  docs/mssql-tools-1.0.0.tgz ???  should we be keeping tar gzipped file in docs?

**Comment by docktermj** [comment]
@ron,  Yes, in fact it needs to be there so that the following command works:

```
helm repo add senzing https://hub.senzing.com/charts/
```

This is much cleaner than having `helm repo add` point into branch on GitHub.

**Comment by roncewind** [comment]
sounds good, docs seems an odd place though?  is it really MS tools?  should we have a tools directory?

**Comment by docktermj** [comment]
@roncewind On the empty NOTES.txt.  Yes, empty for the time being.

**Review by roncewind — APPROVED** [review]

**Comment by docktermj** [comment]
@roncewind This chart is a wrapper for the `mcr.microsoft.com/mssql-tools` docker image.  We don't control it.

**Pull request merged**
